version: 2.1

jobs:
  arduino-ci-test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Install
          command:
            bundle install
      - run:
          name: Test
          command:
            bundle exec arduino_ci_remote.rb | tee first_output.txt
      - run:
          name: Manipulate output
          command:
            python3 .circleci/extractOtput.py | tee /tmp/test_output.txt
      - store_artifacts:
            path: /tmp/test_output.txt
            destination: test_output

workflows:
  arduino-ci-workflow:
    jobs:
      - arduino-ci-test
